package com.samuel.spectrite.client.particles;

public enum EnumSpectriteParticleTypes {
    SPECTRITE_SPELL, SPECTRITE_SMOKE_NORMAL, SPECTRITE_SMOKE_LARGE, SPECTRITE_EXPLOSION_NORMAL, SPECTRITE_EXPLOSION_LARGE, SPECTRITE_EXPLOSION_HUGE
}
